config/routes.rb
Pling::Application.routes.draw do

#  match 'users#new', to: 'companies#register'
#  resources :users, :companies
#  match '/companies' => 'companies#show'
#  match 'companies#show' => 'companies/:company_id/show'

  resources :companies do
    resources :users 
  end

  match '/companies/:company_id/register' => 'users#new' 
  match '/companies/:company_id/new' => 'users#new' 
  
  root :to => redirect("http://www.palmling.com")

  # match '/traveler', to: 'users#new', user_type: "traveler"
  # match '/translator', to: "users#new", user_type: "translator"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users
  
  attr_accessible :name, :phone_number, :logo_file
  before_save :create_permalink

  validates :name, :presence => true, :uniqueness => true
  validates :phone_number, :presence => true  
  validates :logo_file, :presence => true, :uniqueness => true

  def to_param
    permalink
  end
  
  private
       def create_permalink
            self.permalink = name.downcase
       end  
end
# == Schema Information
#
# Table name: companies
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  logo_file  :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  permalink  :string(255)
#

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id           :integer         not null, primary key
#  name         :string(255)
#  email        :string(255)
#  created_at   :datetime        not null
#  updated_at   :datetime        not null
#  user_type    :string(255)
#  referred_by  :string(255)
#  company_id   :string(255)
#  phone_number :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :phone_number, :company_id, :user_type, :referred_by
  belongs_to :company
  #after_create :send_welcome_email
  
  validates :name, :presence => true, length: { maximum: 50 }
  validates :email, :presence => true, :uniqueness => true, length: { maximum: 40 }
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates :phone_number, :presence => true, length: { maximum: 16 }

  #private

  # def send_welcome_email
  #    unless self.email.include?('@palmling.com') && Rails.env != 'test'
  #      UserMailer.welcome_email(@user, @company).deliver
  #    end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  @user_type = ""
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  def new
    redirect_to 'http://palmling.com' #See note below
    #Implement this in production of portal.palmling.com for security
    #until there is finally an authentication system in place    
    @company = Company.new
  end
  
  def index
    redirect_to 'http://palmling.com' 
    @companies = Company.all    
  end

  def show
    @company = Company.find_by_permalink(params[:id])
    #@company.name
  end
  
  def create
    @company = Company.new(params[:company])
    if @company.save
      #flash[:success] = "Company created"
      redirect_to @company        
      #render 'show'  
    else
      render 'new'
    end    
  end

end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  def thanks
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def profile
  end

  def admin
  end

  def register
  end

  def press
  end

  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :load_company
  
  def new
    @user = User.new
    #@user = @company.users.new
    # @company = Company.find_by_name(params[:id])
    # @user.user_type = params[:user_type]
  end

  def show
    @user = User.find(params[:id])
    #@user = @company.users.find(params[:id])
  end

  def index
    redirect_to "http://palmling.com"
  end
    
  def create
    
    @user = @company.users.new(params[:user])
    if @user.save
      UserMailer.welcome_email(@user, @company).deliver
      render 'show'
    else
      render 'new'
      #render :json => { "errors" => @user.errors } 
    end
        
  end
  
  private
  def load_company
    @company = Company.find_by_permalink(params[:company_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo
    logo = image_tag("palmling.png", alt: "PalmLing", class: "round")  
  end  
  
  def full_title(page_title)
    base_title = "PalmLing"
    if page_title.empty?
      base_title
    else
      "#{base_title} - #{page_title}"
    end
  end
    
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/index.html.erb
<div id="company_list" class="whiteness">
	<div class="span6 temp-skype">
		<table>					 
			<tr>
				<td>Company</td>
				<td>&nbsp;&nbsp;&nbsp;&nbsp;Registration URL</td>
			</tr>
			<% @companies.each do |company| %>			
			<tr>
				<td><%= company.name %></td>
				<td>
					<input type=text_field readonly="true" value='<%= company.logo_file %>' style="width:500px">
				</td>
			</tr>
			<% end %>
		</table>				
	</div>
</div>

app/views/companies/new.html.erb
<%= provide(:title, 'Company Creation') %>
<div id="skype-header" class="row span6 offset3">
<!--h1>PalmLing Distribution Portal</h1-->
<h2>Enter company information</h2>
<!--p>Thank you for your interest in PalmLing! Please complete the form below to get started.
</p-->
</div>

<div class="row">
  <div class="span6 offset3 temp-skype">
    <%= form_for(@company) do |f| %>
      <%= f.error_messages %> 

      <%= f.label :name, 'Company name' %>
      <%= f.text_field :name %>

      <%= f.label :logo_file, "Logo's URL" %>
      <%= f.text_field :logo_file %>

      <%= f.label :phone_number, "Phone number" %>
      <%= f.text_field :phone_number, :placeholder => "xxx-xxx-xxxx" %>
			
      <%= f.submit "Create Company", class: "btn btn-large btn-success" %>
			
    <% end %>
  </div>
</div>

app/views/companies/register.html.erb
<%= provide(:title, 'Distribution Portal') %>
<div id="skype-header" class="row span6 offset3">
<h1>PalmLing Distribution Portal</h1>
<h2>Step 1 - Signup</h2>
<p>Thank you for your interest in PalmLing! Please complete the form below to get started.
</p>
</div>

<%= render '/users/new' %>

app/views/companies/show.html.erb
<%= provide(:title, 'Company Show Page') %>
<div id="skype-header" class="row span6 offset3">
<!--h1>PalmLing for Skype</h1>
<h2>Step 2 - Select a Plan</h2-->
<p>Copy this URL. This email is to be used by <span class="skype-name"> <%= @company.name %> employees</span> to register. <br/><!-- Thank you for signing up for PalmLing for Skype! <br />  To get started, please select a plan that fits your needs. -->
	
	<input type=text_field value="<%= HOST_URL %>/companies/<%= @company.permalink %>/register">
	<br/><br/>
	Click <a href='<%= HOST_URL %>/companies/<%= @company.permalink %>/register'>here to go</a> to the registration page for <%= @company.name %> employees.
<!-- Click link_to 'here', new_company_user_path(@company) %> to register -->
</p>


<!-- 'http://localhost/companies/#{@company.permalink}/new' -->

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   'http://www.palmling.com/about_page' %></li>
      <li><%= link_to "FAQs", 'http://www.palmling.com/FAQ' %></li>
      <li><%= link_to "Press", 'http://www.palmling.com/press_palmling' %></li>
      <li><%= link_to "Contact", 'http://www.palmling.com/contact' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
  <div>
    <div class="container">
      <%= link_to logo, 'http://www.palmling.com', id: "logo" %>
	  <div style="float: right">
	  <%
		@company = Company.find_by_permalink(params[:id])
	  	@company ||= Company.find_by_permalink(params[:company_id])
	   %>	
		
	  <% if @company %>
		<img src="<%= @company.logo_file.to_s %>" id="company_logo">
</div>
	  <% end %>
	  <!-- image_tag("#{params[:id]}.png", alt: "IBM", class: "round", :size=>'150x150') %--></div>
	
	  <%= favicon_link_tag 'palmling.ico' %>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://[tangcius.com]?referrer[customer_id]=001&referrer[email]=nicktang@gmail.com&referred[customer_id]=006&referred[email]=002.taiwan@gmail.com" %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
			<div class="container">
			  <%= yield %>
				<!--%= render 'layouts/footer' %-->
				<%= debug(params) if Rails.env.development? %>
			</div>
</body>
</html>

app/views/layouts/v2/application.html.erb
<%= render ('shared/app_header') %>
<!-- probably need messages here --> 
<%= yield %>
<%= render ('shared/app_footer') %>

app/views/layouts/v2/home.html.erb
<% content_for :footer_js do %>
 <%= javascript_include_tag "init_carousel" %>
<% end %>

<%= render ('shared/just_head') %>
<body class="home">
<header>
	<% flash.each do |key, value| %>
	  <div style="text-align: right" class="alert alert-<%= key %>"><%= value %></div>
	<% end %>
<a class="business-fold" href="#"></a>
    <div class="container">
        <div class="span5">
            <div class="topnav">
                <%= render('shared/header_nav') %>
            </div>
            <div class="logo-wrapper">
                <%= image_tag "logo.png", :alt => "VerbalizeIt.com", :class => 'logo' %>
                <%= image_tag "tagline.png", :alt => "human translators. any language. any device. any time", :class => 'tagline' %>
            </div>
        </div><!-- ./columns -->
        <div id="icons" class="span1">
            <a id="s-icon" class="product-icon smartphone" href="s-desc"></a>
            <a id="o-icon" class="product-icon oldphone" href="o-desc"></a>
            <a id="w-icon" class="product-icon web" href="w-desc"></a>
            <a id="a-icon" class="product-icon api" href="a-desc"></a>
        </div>
        <div id="tabs">
            <div id="s-desc" class="span6 product-description smartphone">
                <div class="desc-inner">
                    <h2>Get the app for your iPhone or Android device</h2>
                    <%=  link_to image_tag("app-app-store.png"), '#', :class => 'app-store' %>
                    <%=  link_to image_tag("app-android.png"), '#', :class => 'android' %>
                    <%= image_tag "iphone-mockup.png", :alt => "VerbalizeIt App for iPhone and Android", :class => 'teaser' %>
                    
                </div>
            </div><!-- ./columns-->
            <div id="o-desc" class="span6 product-description oldphone">
                <div class="desc-inner">
                    <h2>Have an older phone? No problem. We've got you covered.</h2>
                    <p>Just sign up for an account to try it for free.</p>
                    <%= link_to "Try for Free", '#', :class => "leadbutton" %>
                </div>
            </div><!-- ./columns-->
            <div id="w-desc" class="span6 product-description web">
                <div class="desc-inner">
                    <h2>Get the verbalizeit widget for your web site and start communicating with visitors from around the world.</h2>
                    <p>Drop a line to find out how to integrate verbalizeit on your site today.</p>
                    <%= link_to "Contact Us", '#', :class => "leadbutton" %>
                    
                </div>
            </div><!-- ./columns-->
            <div id="a-desc" class="span6 product-description api">
                <div class="desc-inner">
                    <h2>Use the verbalizeit API to take advantage of our platform in your web app, mobile app, or anywhere.</h2>
                    <p>Sign up to be notified when the API is publicly available. (We promise not to share your email address.)</p>
					
                    <!-- <form class="form">
                        <input type="text" placeholder="youraddress@email.com"><a class="submit leadbutton" href="#">Sign Up</a>
                    </form> -->
                </div>
            </div><!-- ./columns-->
        </div><!-- ./tabs -->
    </div><!-- container -->
    <div class="heavydivide"></div>
</header>

    <section class="testimonials">
        <div class="container">
            <%= image_tag "testimonial-fade-left.png",:class => 'fader left' %>
            <%= image_tag "testimonial-fade-right.png", :class => 'fader right' %>
            <div id="myCarousel" class="container-inner carousel slide"><!-- width and position will be calculated on the fly by js -->
             
            <%= render ('shared/home_slider') %>    
       
            </div>
        </div><!-- ./container -->
    </section>

       <section class="map">
        <div class="container">
            <div class="map-title">We’re All Over — Here are some people using <span class="highlight">verbalizeit</span> right now</div>
            <div class="map-container"></div>
        </div><!-- ./container -->
        </section><!-- ./section -->
<%= render ('shared/just_footer') %>

app/views/layouts/v2/translator.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

    <meta charset="utf-8">
    <title>verbalize.it</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Varela|Varela+Round">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet/less" href="css/styles.less">

    <link rel="shortcut icon" href="img/favicon.ico">

</head>
<body class="inner">

    <header>
        <div class="container">
            <a class="signin" href="#">Sign in</a>
            <a href="/"><img class="logo" src="img/logo.png" alt="Verbalize.it"></a>
        </div><!-- container -->
    </header>

    <section class="map translatorstories">
        <div class="caption">
            <div class="container">
                Lin Mei lives in New York. She speaks English and Mandarin, <br> and wants to earn some extra money between classes.
            </div>
        </div>
        <div class="container">
            <div class="map-container">
                <img src="img/translator-story-user1.png" class="user1">
                <img src="img/translator-story-user2.png" class="user2">
                <img src="img/translator-story-translator.png" class="translator">
                <div class="indicators">
                    <a href="#" class="active"></a>
                    <a href="#"></a>
                    <a href="#"></a>
                    <a href="#"></a>
                    <a href="#"></a>
                    <a href="#"></a>
                </div>
            </div>
        </div><!-- ./container -->
    </section>

    <section class="process">
        <div class="container">

            <div class="span12"><h1>Become a translator in just in 5 minutes</h1><br></div>
            <div class="span4 step">
                <img src="img/process-arrow.png">
                <h2>Sign Up</h2>
                <p>Give us your phone number <br> and a few other details.</p>
            </div>
            <div class="span4 step">
                <img src="img/process-arrow.png">
                <h2>Show Your Skills</h2>
                <p>Take a quick profficiency test <br> in your languages.</p>
            </div>
            <div class="span4 step">
                <h2>Start Translating</h2>
                <p>Earn money by translating <br> conversations in your free time.</p>
            </div>
            <div class="span12">
                <br><a href="#" class="signup">Cool, Sign Me Up</a>
            </div>

        </div><!-- ./container -->
    </section>

    <section class="content">
        <div class="container">

            <div class="span12">
                <h2>Frequently Asked Questions</h2><br>
            </div>

            <div class="span6">

                <h3>Q: I want to join! How do I sign up?</h3>
                <p class="minor">Simply click here to register. Registration is quick and simple.</p>

                <h3>Q: Why should I become a VerbalizeIt translator?</h3>
                <p class="minor">Because you want to help travelers navigate the barriers to communication while visiting a country in which they do not speak the native language, of course! Plus, VerbalizeIt is a great place to work. Translators join the VerbalizeIt family, a community of fun and talented individuals who are passionate about language, travel and helping others make the most of their travels. We could tell you about all of the benefits of joining the VerbalizeIt community, but that would spoil all of the surprises!</p>

                <h3>Q: I know other people who’d be great translators.</h3>
                <p class="minor">Our best friend (next to a dog) is a referral from a customer or visitor who values our service. Click here to refer a customer or translator. We love referrals so much that we reward you for referring VerbalizeIt to others. to learn more.</p>

                <h3>Q: How can I earn money as a translator?</h3>
                <p class="minor">Follow our simple registration process, demonstrate your proficiency during our language test and provide exceptional service to VerbalizeIt customers. Translators are awarded based on the quality of their translations and their availability to do so.</p>

                <h3>Q: Why do you need my phone number?</h3>
                <p class="minor">Two reasons: One, we need to administer a language proficiency test. Two, our platform will route customer phone calls directly to your phone when you mark yourself available to translate.</p>

            </div>

            <div class="span6">
                
                <h3>Q: Why do you need my tax information?</h3>
                <p class="minor">Our payroll processing system requires your tax information in order to ensure compliance with U.S. tax laws.</p>

                <h3>Q: Why must I take a language proficiency test in order to be approved?</h3>
                <p class="minor">We only want the most qualified, dedicated and accountable translators to join the VerbalizeIt community. Put yourself in the shoes of a traveler – wouldn’t you want the best and brightest to take your call? We think so.</p>

                <h3>Q: I missed the proficiency test call. What should I do?</h3>
                <p class="minor">It happens. Please email us at admin@verbalizeit.com to reschedule. We’ll find another time for you!</p>

                <h3>Q: How much time or scheduling flexibility do I need to join VerbalizeIt?</h3>
                <p class="minor">Our platform works with even the busiest of schedules, so even if you have only a short period of time to make yourself available to translate, VerbalizeIt is still right for you.</p>

                <h3>Q: I’m signed up! Now what?</h3>
                <p class="minor">Upon registering, you indicated several times for when you are available to take the proficiency test. Please wait for one of our testers to contact you.</p>

            </div>

   <%= render ('shared/footer') %>

app/views/layouts/v2/translator_home.html.erb
<%= render ('shared/head') %>
<body class="inner">

    <header>
        <div class="container">
        <a class="signin" href="#">Sign in</a>    
            
        <%=  link_to image_tag("v2/logo.png", :alt => 'Verbalize.it', :class => 'logo'), root_path %>
        </div><!-- container -->
    </header>

    <section class="map translatorstories">
        <div class="caption">
            <div class="container">
                Lin Mei lives in New York. She speaks English and Mandarin, <br> and wants to earn some extra money between classes.
            </div>
        </div>
        <div class="container">
            <div class="map-container">
                <%= image_tag "v2/translator-story-user1.png",:class => 'user1' %>
                <%= image_tag "v2/translator-story-user2.png",:class => 'user2' %>
                <%= image_tag "v2/translator-story-translator.png",:class => 'translator' %>
              
                <div class="indicators">
                    <a href="#" class="active"></a>
                    <a href="#"></a>
                    <a href="#"></a>
                    <a href="#"></a>
                    <a href="#"></a>
                    <a href="#"></a>
                </div>
            </div>
        </div><!-- ./container -->
    </section>

    <section class="process">
        <div class="container">

            <div class="span12"><h1>Become a translator in just in 5 minutes</h1><br></div>
            <div class="span4 step">
                <img src="img/process-arrow.png">
                <h2>Sign Up</h2>
                <p>Give us your phone number <br> and a few other details.</p>
            </div>
            <div class="span4 step">
                <img src="img/process-arrow.png">
                <h2>Show Your Skills</h2>
                <p>Take a quick profficiency test <br> in your languages.</p>
            </div>
            <div class="span4 step">
                <h2>Start Translating</h2>
                <p>Earn money by translating <br> conversations in your free time.</p>
            </div>
            <div class="span12">
                <br><a href="#" class="signup">Cool, Sign Me Up</a>
            </div>

        </div><!-- ./container -->
    </section>

  

            

   <%= render ('shared/footer') %>

app/views/layouts/v2/translators-nw.html.erb
<%= render ('shared/head') %>
<body class="inner">

    <%= render ('shared/main_header_nav') %>

    <%= yield %>

  

            

   <%= render ('shared/footer') %>

app/views/layouts/v2/translators.html.erb
<%= render ('shared/just_head') %>
<body class="inner">
	<%= render ('shared/header_tag') %>
	<%= yield %>

<%= render ('shared/just_footer') %>

app/views/referrals/thanks.html.erb
<% provide(:title, 'Thanks') %>
<% @dudeID = '13' %>
<div class="center hero-unit">
  <h1>Thanks</h1>

  <h2>
    This is the about page for
    <a href="#/">pling</a>.
  </h2>
	
  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<%= javascript_tag do %>
	window.dude_id = '<%= j @dudeID %>';
<% end %>

app/views/shared/_TODELETE_footer.html.erb
           </div><!-- ./container -->
    </section><!-- ./section -->
    <footer>
        <div class="container affiliates">
            <div>as seen on</div>
            
            <%= link_to "", '#', :class => "travelchannel" %>
            <%= link_to "", '#', :class => "nationalgeographic" %>
            <%= link_to "", '#', :class => "frommers" %>
            <%= link_to "", '#', :class => "lonelyplanet" %>
            <%= link_to "", '#', :class => "fodors" %>
            <%= link_to "", '#', :class => "kayak" %>
        </div><!-- ./container -->
        <div class="container links">
            <ul class="span3">
                <li class="title">more about verbalize.it</li>
                <li><%= link_to "about us", about_path%></li>
                <li><%= link_to "the team", the_team_path%></li>
                <li><%= link_to "traveler FAQ", traveler_faq_path%></li>
                <li><%= link_to "press", press_path%></li>
            </ul>
            <ul class="span3">
                <li class="title">our services</li>
                <li><%= link_to "pricing", '#'%></li>
                <li><%= link_to "group rates", '#'%></li>
                <li><%= link_to "business rates", '#'%></li>
                <li><%= link_to "verbalize.it for your site", '#'%></li>
            </ul>
            <ul class="span3">
                <li class="title">translators</li>
                <li><%= link_to "translator FAQ", interpretor_faq_path %></li>
                <li><%= link_to "become a translator", translator_landing_path %></li>
            </ul>
            <ul class="span3 contact">

                <li> <%= link_to "follow us on twitter", '#', :class => "twitter" %></li>
                <li> <%= link_to "follow us on facebook", '#', :class => "facebook" %></li>
                <li> <%= link_to "drop an email", '#', :class => "email" %></li>
                <li> <%= link_to "give us a call", '#', :class => "call" %></li>
            </ul>
        </div><!-- ./container -->
        <div class="container copyright">
            Copyright 2012, Verbalize.it Inc  All Rights Reserved.
        </div><!-- ./container -->
    </footer>
    <%= javascript_include_tag "v2/jquery-min.js", "v2/underscore-min.js", "v2/backbone-min.js", "v2/bootstrap.min.js","v2/less-min.js", "bootstrap-carousel.js" %>
    <script type="text/javascript">
      $(document).ready(function(){

        $('.carousel').carousel({
            interval: 3000
        })
      });
    </script>
    <!--
    <script type="text/javascript">
         document.write(unescape("%3Cscript src='" + ((document.location.protocol=="https:")?"https://snapabug.appspot.com":"http://www.snapengage.com") + "/snapabug.js' type='text/javascript'%3E%3C/script%3E"));</script>
    <script type="text/javascript">
     SnapABug.addButton("a656be5c-d0dc-4b4f-b255-aa24d5fbf2c6","0","55%");
     </script>
     -->
    
   
    <!--[if lt IE 9]>
        <script src="v2/html5shiv.js"></script>
    <![endif]-->

</body>
</html>

app/views/shared/_TODELETE_header.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <title>verbalize.it | <%= yield(:title) %></title>
    <meta content="VerbalizeIt - Human Translation in the Palm of your Hand." property="og:title" />
    <meta content="business" property="og:type" />
    <meta content="http://www.verbalizeit.com/home?" property="og:url" />
    <meta content="http://www.verbalizeit.com/images/verbalizeitfb.png" property="og:image" />
    <meta content="VerbalizeIt" property="og:site_name" />
    <meta content="dredworks" property="fb:admins" />
    <meta content="Travel with confidence. Travel with VerbalizeIt." property="og:description" />

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag "v2/bootstrap.min.css", "http://fonts.googleapis.com/css?family=Varela|Varela+Round" %>
    
    <%= stylesheet_link_tag "v2/styles.less", :rel => "stylesheet/less" %>
    <%= stylesheet_link_tag "v2/styles2.css"%>
    <link rel="shortcut icon" href="img/favicon.ico">


</head>
<body class="inner">

    <%= render ('shared/main_header_nav') %>
    <% if content_for? :main_section_content_class %>
     <%= yield :main_section_content_class %>
    <% else %>
        <section class="content">
     
    <% end %>
        <div class="container">
    <%= render ('/layouts/v2/messages') %>

app/views/shared/_TODELETEmain_header_nav.html.erb
   <header>
        <div class="container">
           <div class="topnav">

                <%= link_to "be a translator", translator_home_path %> |
                <%= link_to "pricing", '#' %> |
                <%= link_to "about us", about_path %> |
                <% if signed_in? %>
                  <%= link_to('sign out', destroy_translator_session_path) if current_translator  %>   
                  <%= link_to('sign out', destroy_customer_session_path) if current_customer  %>      
                <% else %>
                  <%= link_to('sign in', new_customer_session_path, :method => :get)  %>    
                  
                <% end %>

            </div>
            <a href="/"><%=  link_to image_tag("v2/logo.png", :class => 'logo', :alt => 'Verbalize.it'), root_path %></a>
        </div><!-- container -->
        <div class="heavydivide"></div>
    </header>

app/views/shared/_head.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

    <meta charset="utf-8">
    <title>verbalize.it</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag "v2/bootstrap.min.css", "http://fonts.googleapis.com/css?family=Varela|Varela+Round" %>
    
    <%= stylesheet_link_tag "v2/styles.css" %>
    <%= stylesheet_link_tag "v2/styles2.css"%>
    <link rel="shortcut icon" href="img/favicon.ico">

</head>

app/views/static_pages/register.html.erb
<% provide(:title, 'Register') %>
Sign up...yeaaHHHH